### ISSUE TITLE
optional arguments for non-global caching

### ISSUE THREAD

**Issue by xzackli** [Jutho/WignerSymbols.jl#12]
Thanks for writing a really great package! I have a feature request, and I'd be happy to eventually do the work for it if you don't have the time. (Also please close this issue if you think it doesn't belong in the package, I'm cognizant that I'm a random person on the internet asking for changes to your work!)

I want to call `wigner3j` from multiple threads, but I believe it would be unsafe due to the global tables used for caching. One way forward would be to allow an optional parameter for `wigner3j` of some kind of `PrimeCaches{T}` struct containing the arrays and `T <: AbstractDict`. If not specified, this would look for the global prime cache, similar to the behavior of RNGs.

This would not change the single-threaded API or performance, but would let me maintain thread-local copies of the caches for multithreading. In a future where there are packages for thread-safe data structures in Julia, you could pass a global set of atomic dicts and arrays. As a bonus, it'd be easier to serialize caches to disk, since this would pack up all the tables into a struct.

**Comment by Jutho** [comment]
Hi @xzackli , that sounds like a very good proposal. I am not familiar with how the `Random` standard library deals with this, so if you have experience and are willing to prepare a PR, that's definitely a welcome addition.
