### ISSUE TITLE
Thread-safety

### ISSUE THREAD

**Issue by jagot** [Jutho/WignerSymbols.jl#14]
Related to #12 & #13.

I got bitten by this today, when I noticed that rotation matrices built from Clebsch--Gordan coefficients were no longer unitary, and a little later Julia crashed because of `undefined reference` when trying to access the factorial table out-of-bounds.

I appreciate that making WignerSymbols.jl fully thread-safe, while desirable, is a major undertaking. As a stop-gap solution, can I "warm start" by computing a large factorial once, populating the cache to cover all cases I will later need in the threaded section? I rarely need larger angular momenta than a few hundred.

**Comment by Jutho** [comment]
I've just released v2.0 which is thread safe. It was a major undertaking indeed, but I believe it was a necessary one.

**Comment by jagot** [comment]
Wohoo, thanks! Will check it out pronto.

**Comment by Jutho** [comment]
Ok, I am in particular interested to know your impressions if you are working on a Windows. CI was giving some unexpected failures on Windows, but I don't have a Windows machine to test it locally. So I disabled the use of multiple threads on Windows for the CI.

I've made several reasoning mistakes about thread safety during the developments, but I don't see what could still go wrong now, and on Linux and Mac everything seems to be working fine.

**Comment by jagot** [comment]
Sadly (or maybe not?) I'm not using Windows either, only Mac and Linux. I will see if I know someone who can test running my code which is dependent on WignerSymbols.jl on a real Windows machine.

**Comment by Jutho** [comment]
Any Mac or Linux experiences, in particular with respect to performance, are certainly also welcome :-)

**Comment by Jutho** [comment]
Hi @jagot ; did you have any impressions or concerns to share, or where you not yet able to test the new version of WignerSymbols?

**Comment by jagot** [comment]
It just seems to work 😊 I run my calculations in threaded mode (although not very efficiently threaded...), and I have had no problems so far.

**Comment by Jutho** [comment]
Great to hear; thanks for confirmation.
