### ISSUE TITLE
Add test for Wigner 3-j symbol orthogonality relations

### ISSUE THREAD

**Issue by arturgower** [Jutho/WignerSymbols.jl#7]
The [orthogonality relations](https://en.wikipedia.org/wiki/3-j_symbol#Orthogonality_relations) are a nice test, as they only pass if all properties are correct. 

Also, I'm not sure that the Clebsh-Gordan coefficients are defined the same way across physics, where as the Wigner 3j are. So the orthogonality test for the Wigner 3j gives confidence to users.

**Comment by arturgower** [comment]
Note, am going to write this test and create pull request for it.

**Comment by Jutho** [comment]
Great!
